### ISSUE TITLE
Feedback - 15-Nov-2021

### ISSUE THREAD

**Issue by achobanov** [HorseSport-achobanov/endurance-judge#23]
[2021-11-15.docx](https://github.com/HorseSport-achobanov/endurance-judge/files/7589737/2021-11-15.docx)
## Tasks
- [x] Phase.Length -> double
- [x] Final phase - no rest
- [x] Remove button - popup
- [x] Errors in popup
- [x] Add participant.Number in display name
- [x] Change numbers inputs to nullable
